### ISSUE TITLE
FPS Calculation Bug

### ISSUE THREAD

**Issue by lfelipesv** [KleinYuan/tf-object-detection#10]
I am getting negative values to the FPS using the object_detection program.

I think it is related to calculating the time difference with datetime.datetime.now().microsecond * 0.001

It can be solves using datetime.datetime.now().utcnow() i think, or using other module to calculate the fps rate like 'timeit' package.

Your code is clean and a good wrapper to the tensorflow object detection module.

Cheers!

**Comment by KleinYuan** [comment]
@lfelipesv Thanks!
Yep, that makes sense. I actually would like to remove that since it's kinda confusing and TBH that logging code is not that clean.
Thanks for pointing out.

**Comment by KleinYuan** [comment]
@lfelipesv 
I [removed the fps](https://github.com/KleinYuan/tf-object-detection/commit/1bb57b36d2ce8117ba0507caed07375e9bf07073) since I will slowly try to make this repo compatible for both Python 2&3. Therefore, I will just remove such redundant code.

I assume this should be resolved and shall we close this issue?

**Comment by KleinYuan** [comment]
Closed due to no feedback and issue resolved.
If any concerns, reopen it.
