### ISSUE TITLE
How can I train my models with my images ？

### ISSUE THREAD

**Issue by Yinpenguin** [KleinYuan/tf-object-detection#12]
How can I train my models with my images ？ thank you ！ @KleinYuan

**Comment by KleinYuan** [comment]
@Yinpenguin Hi,

This repo's scope is purely to provide an object detection API and that's it.

Training code is out of the scope and if you are interested, you should try to refer to [tensorflow/models](https://github.com/tensorflow/models/blob/master/research/object_detection/train.py).

**Comment by KleinYuan** [comment]
I also organized a project with simple [building blocks](](https://github.com/KleinYuan/tf-blocks/blob/master/apps/cnn_training_app.py)) to help you finish the training task, where you just need to simply fill in the network architecture.

Since this issue is out side of this repo's scope and I will close it until you have more questions or responses. Feel free to reopen if you feel necessary.

**Comment by Yinpenguin** [comment]
OK,I see. Many thanks for your kind help.
